### ISSUE TITLE
Combo-Box Menu Background is Transparent

### ISSUE THREAD

**Issue by alnadev** [oqipoDev/garden-gnome-obsidian#1]
I have noticed the combo-box widget is using a transparent background, which is an inconsistency between the "garden-gnome-obsidian" and the GTK4 Adwaita theme.

### Combo-Box Appearance in Obsidian's settings window

The Combo-Box widget is hard to be differentiated as a regular text or an interactable widget. Therefore, its background colour should be different from the widget behind it.

#### Dark

![transparent_background_combo-boxes](https://github.com/oqipoDev/garden-gnome-obsidian/assets/81011910/00ee6b92-2fdd-4b45-be74-feb39ca7f772)

#### Light

![light-demo-example](https://github.com/oqipoDev/garden-gnome-obsidian/assets/81011910/6b8cb280-053e-445a-8dcc-b9a1cad6f21b)

### Combo-Box Appearance on a native GTK Application

Its styling should be similar to this.

#### Dark

![demo-example](https://github.com/oqipoDev/garden-gnome-obsidian/assets/81011910/142ac6fa-b64f-40e2-943b-3edecddebce6)

#### Light

![light-demo-example](https://github.com/oqipoDev/garden-gnome-obsidian/assets/81011910/e1651777-f9ba-4007-b5f0-eaee5d2f5906)

**Comment by oqipoDev** [comment]
You're right, that's a better design. I originally based it off of the GNOME settings app and it seemed odd to me but I didn't think much of it. I'll fix it later today :]
