### ISSUE TITLE
Stacked view for tabs is broken

### ISSUE THREAD

**Issue by dhniceday** [oqipoDev/garden-gnome-obsidian#3]
Close button is in the middle. Note title only shows on hover. Note title tab is much too large. 
(or is this intentional ?) 

![Bildschirmfoto vom 2024-01-04 21-45-40](https://github.com/oqipoDev/garden-gnome-obsidian/assets/3727327/686da7f1-29c6-4fbb-8377-4eee00b8c41c)

Possible to fix it ? Thank you.

**Comment by oqipoDev** [comment]
Sorry, I didn't make this theme considering vertical tabs. I don't think I can fix it this week, but I might start looking into it tomorrow, any suggestions are welcome :]

**Comment by oqipoDev** [comment]
I added a fix, so let me know how it works for you @dhniceday

**Comment by dhniceday** [comment]
I got up this morning and it's already fixed :-) Thank you !
